package giaodien;

import java.util.Collections;
import java.util.List;
import java.util.Random;

import laydulieu.DuLieuBienDongChungKhoan;
import laydulieu.DuLieuChiSoINDEX;
import laydulieu.DuLieuChungKhoanTheoNgay;
import laydulieu.DuLieuNhaDauTuNuocNgoai;
import sinhcau.SinhCauBienDongChungKhoan;
import sinhcau.SinhCauChiSoINDEX;
import sinhcau.SinhCauNhaDauTuNuocNgoai;
import sinhcau.SinhCauTheoNgay;
import tintuc.ChiSoChungKhoan;
import tintuc.CoDongChungKhoan;
import tintuc.CoPhieuChungKhoan;
import tintuc.CoTucChungKhoan;
import tintuc.GiaChungKhoan;
import tintuc.GiaiNganChungKhoan;
import tintuc.LoiNhuanChungKhoan;
import tintuc.NhaDauTuChungKhoan;
import tintuc.PhienChungKhoan;
import tintuc.SanGiaoDichChungKhoan;
import tintuc.ThanhKhoanChungKhoan;
import tintuc.TraiPhieuChungKhoan;
import visualize.plot.Plot;

/**
 *
 * @author Tu
 */
public class MainJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainJFrame
	 */
	String[] list = { "HNX", "HSX", "UPCOM" };
	Random rd = new Random();
	SinhCauChiSoINDEX VN_INDEX = new SinhCauChiSoINDEX();
	// SinhCauChiSoINDEX VN30_INDEX = new SinhCauChiSoINDEX();
	SinhCauBienDongChungKhoan bienDong = new SinhCauBienDongChungKhoan();
	SinhCauNhaDauTuNuocNgoai nuocNgoai = new SinhCauNhaDauTuNuocNgoai();
	SinhCauTheoNgay cauTheoNgay = new SinhCauTheoNgay();

	public void inThongTin(List<String> p) {
		Collections.shuffle(p);
		for (int i = 0; (i < 5); i++) {
			try {
				String s = p.get(i);
				jTextArea1.append(s + "\n");
			} catch (Exception ex) {
				System.out.println("Rỗng");
			}
		}
	}

	public void inTatCa(List<String> p) {
		p.stream().forEach((s) -> {
			jTextArea1.append(s + "\n");
		});
	}

	public MainJFrame() {
		initComponents();
		setTitle("Chứng Khoán");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollBar1 = new javax.swing.JScrollBar();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jSpinner1 = new javax.swing.JSpinner();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jPanel5 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jPanel6 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jList1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 1175, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		jPanel2.setBackground(new java.awt.Color(0, 0, 255));

		jPanel4.setBackground(new java.awt.Color(255, 0, 0));

		jLabel2.setBackground(new java.awt.Color(255, 0, 0));
		jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_android_black_18dp.png"))); // NOI18N
		jLabel2.setText("CHỨNG KHOÁN");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(26, 26, 26).addComponent(jLabel2)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
						.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(0, 255, 0));
		jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_fiber_new_black_18dp.png"))); // NOI18N
		jLabel1.setText("TIN TỨC CHỨNG KHOÁN");

		jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Chỉ số chứng khoán", "Cổ phiếu chứng khoán", "Cổ đông chứng khoán", "Phiên chứng khoán",
						"Giá chứng khoán", "Cổ tức chứng khoán", "Giải ngân chứng khoán", "Lợi nhuận chứng khoán",
						"Nhà đầu tư ", "Thanh khoản", "Sàn giao dịch", "Trái phiếu", " " }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
						.addContainerGap()));

		jPanel5.setBackground(new java.awt.Color(0, 255, 0));
		jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_timeline_black_18dp.png"))); // NOI18N
		jLabel3.setText("BIỂU ĐỒ CHỨNG KHOÁN");

		jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jComboBox2.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "VNINDEX", "VN30INDEX", "VN100-INDEX", " " }));
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
						.addContainerGap()));

		jPanel6.setBackground(new java.awt.Color(0, 255, 0));
		jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baseline_description_black_18dp.png"))); // NOI18N
		jLabel4.setText("SINH CÂU CHỨNG KHOÁN");

		jComboBox3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biến động chứng khoán", "Chỉ số INDEX",
				"Nhà đầu tư nước ngoài", "Chứng khoán theo ngày", " " }));
		jComboBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
						.addContainerGap()));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBox3)
						.addContainerGap()));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addGap(5, 5, 5)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(5, 5, 5)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(20, 20, 20)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(20, 20, 20)
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
						.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(20, 20, 20)));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane2))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		if ("Chỉ số chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN CHỈ SỐ CHỨNG KHOÁN \n");
			inThongTin(ChiSoChungKhoan.chiSo);
		}
		if ("Cổ phiếu chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN CỔ PHIẾU CHỨNG KHOÁN \n");
			inThongTin(CoPhieuChungKhoan.coPhieu);
		}
		if ("Cổ đông chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN CỔ ĐÔNG CHỨNG KHOÁN \n");
			inThongTin(CoDongChungKhoan.coDong);
		}
		if ("Cổ tức chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN CỔ TỨC CHỨNG KHOÁN \n");
			inThongTin(CoTucChungKhoan.coTuc);
		}
		if ("Giá chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN GIÁ CHỨNG KHOÁN \n");
			inThongTin(GiaChungKhoan.gia);
		}
		if ("Giải ngân chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN GIẢI NGÂN CHỨNG KHOÁN \n");
			inThongTin(GiaiNganChungKhoan.giaiNgan);
		}
		if ("Lợi nhuận chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN LỢI NHUẬN CHỨNG KHOÁN \n");
			inThongTin(LoiNhuanChungKhoan.loiNhuan);
		}
		if ("Nhà đầu tư chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN NHÀ ĐẦU TƯ CHỨNG KHOÁN \n");
			inThongTin(NhaDauTuChungKhoan.nhaDauTu);
		}
		if ("Phiên chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN PHIÊN CHỨNG KHOÁN \n");
			inThongTin(PhienChungKhoan.phien);
		}
		if ("Sàn giao dịch chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN SÀN GIAO DỊCH CHỨNG KHOÁN \n");
			inThongTin(SanGiaoDichChungKhoan.sanGiaoDich);
		}
		if ("Thanh khoản chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN THANH KHOẢN CHỨNG KHOÁN \n");
			inThongTin(ThanhKhoanChungKhoan.thanhKhoan);
		}
		if ("Trái phiếu chứng khoán".equals(jComboBox1.getSelectedItem().toString())) {
			jTextArea1.append("TIN TRÁI PHIẾU CHỨNG KHOÁN \n");
			inThongTin(TraiPhieuChungKhoan.traiPhieu);
		}
	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox3ActionPerformed
		if ("Biến động chứng khoán".equals(jComboBox3.getSelectedItem().toString())) {
			jTextArea1.append("SINH CÂU BIẾN ĐỘNG CHỨNG KHOÁN \n");
//          inTatCa(SinhCauBienDongChungKhoan.sentences);
			bienDong.setDataList(
					DuLieuBienDongChungKhoan.CSV_Extract("C:\\Users\\Tu\\Desktop\\BienDongChungKhoan1.csv"));
			bienDong.listModify();
			bienDong.sentences.clear();
			bienDong.sinhDoanVan();
			inTatCa(SinhCauBienDongChungKhoan.sentences);
		}
		if ("Chỉ số INDEX".equals(jComboBox3.getSelectedItem().toString())) {
			jTextArea1.append("SINH CÂU CHỈ SỐ INDEX \n");
//          inTatCa(SinhCauChiSoINDEX.sentences);
			VN_INDEX.setDataList(DuLieuChiSoINDEX.CSV_Extract("C:\\Users\\Tu\\Desktop\\VN_INDEX.csv", "VN_INDEX"));
			VN_INDEX.sentences.clear();
			VN_INDEX.sinhDoanVan();
			inTatCa(SinhCauChiSoINDEX.sentences);
		}
		if ("Nhà đầu tư nước ngoài".equals(jComboBox3.getSelectedItem().toString())) {
			jTextArea1.append("SINH CÂU NHÀ ĐẦU TƯ NƯỚC NGOÀI \n");
//          inTatCa(SinhCauNhaDauTuNuocNgoai.sentences);
			nuocNgoai.setDataList(DuLieuNhaDauTuNuocNgoai.CSV_Extract("C:\\Users\\Tu\\Desktop\\NhaDauTuNuocNgoai.csv"));
			nuocNgoai.setSanGiaoDich("HOSE");
			nuocNgoai.setDate("16/06/2020");
			nuocNgoai.setTongKhoiLuongMuaBan();
			nuocNgoai.sentences.clear();
			nuocNgoai.sinhDoanVan();
			inTatCa(SinhCauNhaDauTuNuocNgoai.sentences);
		}
		if ("Chứng khoán theo ngày".equals(jComboBox3.getSelectedItem().toString())) {
			jTextArea1.append("SINH CÂU CHỨNG KHOÁN THEO TỪNG NGÀY \n");
//          inTatCa(SinhCauTheoNgay.sentences);

			String ma = list[rd.nextInt(3)];
			int ngay = rd.nextInt(5) + 8;
			String file = "C:\\Users\\Tu\\Desktop\\CafeF\\CafeF." + ma + "." + ngay + ".06.2020.csv";
			cauTheoNgay.datalist = DuLieuChungKhoanTheoNgay.CSV_Extract(file, ma);
			cauTheoNgay.sentences.clear();
			cauTheoNgay.sinhDoanVan();
			inTatCa(SinhCauTheoNgay.sentences);
		}
	}// GEN-LAST:event_jComboBox3ActionPerformed

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
//        if("Biểu đồ VNINDEX".equals(jComboBox2.getSelectedItem().toString())) {
//          try {
//		Plot.launch("VNINDEX", " GD khớp lệnh (khối lượng)");
//		} catch (Exception e) {
//			System.out.println("Mã code hoặc thông tin cần truy xuất không tồn tại");
//			e.printStackTrace();
//		}
//	}
//        if("Biểu đồ VN30INDEX".equals(jComboBox2.getSelectedItem().toString())) {
//          try {
//		Plot.launch("VN30INDEX", " GD khớp lệnh (giá trị)");
//		} catch (Exception e) {
//			System.out.println("Mã code hoặc thông tin cần truy xuất không tồn tại");
//			e.printStackTrace();
//		}
//	}
//        if("Biểu đồ VN100-INDEX".equals(jComboBox2.getSelectedItem().toString())) {
//          try {
//		Plot.launch("VN100-INDEX", " GD khớp lệnh (khối lượng)");
//		} catch (Exception e) {
//			System.out.println("Mã code hoặc thông tin cần truy xuất không tồn tại");
//			e.printStackTrace();
//		}
//	}
		try {
			Plot.launch(jComboBox2.getSelectedItem().toString(), " GD khớp lệnh (khối lượng)");
		} catch (Exception e) {
			System.out.println("Mã code hoặc thông tin cần truy xuất không tồn tại");
			e.printStackTrace();
		}
	}// GEN-LAST:event_jComboBox2ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollBar jScrollBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSpinner jSpinner1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables
}
